# Generated by Django 5.1.7 on 2025-05-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField()),
                ('content', models.TextField()),
                ('blog_type', models.CharField(choices=[('home', 'Home Page'), ('about', 'About Us Page'), ('services', 'Services Page')], max_length=20)),
            ],
        ),
    ]
