# Generated by Django 5.1.7 on 2025-05-02 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_blogresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogResponse',
        ),
    ]
